export const GET_BANK_DETAILS = "GET_BANK_DETAILS";
export const GET_BANK_DETAILS_SUCCESS = "GET_BANK_DETAILS_SUCCESS";
export const UPDATE_BANK_DETAILS = "UPDATE_BANK_DETAILS";
export const UPDATE_BANK_DETAILS_SUCCESS = "UPDATE_BANK_DETAILS_SUCCESS";
export const ADD_BANK_DETAILS = "ADD_BANK_DETAILS";
export const ADD_BANK_DETAILS_SUCCESS = "ADD_BANK_DETAILS_SUCCESS";

